### ISSUE TITLE
hydra.errors.InstantiationException: Error locating target 'agents.models.bc.bc_agent.BC_Agent'

### ISSUE THREAD

**Issue by BrightMoonStar** [ALRhub/MaIL#3]
Hello, while running the script bash script/bc/libero_so_bc_mamba_dec.sh, I keep encountering the error hydra.errors.InstantiationException: Error locating target 'agents.models.bc.bc_agent.BC_Agent', see chained exception above. full_key: agents, which prevents the code from running correctly. I have tried many methods to resolve it but without success. Could you please provide some assistance?

**Comment by xiaogangjia** [comment]
Sorry for the late reply, I was super busy last week. Could you add `HYDRA_FULL_ERROR=1` and report the full error? If we still cannot find the error, I can arrange a meeting to help you solve it.

**Comment by mtiezzi** [comment]
Hello, thanks for your work!
I am facing the same issues above. I installed the project following the readme, on a new conda environment.  Could you help me solve the issue?

 For instance, when trying to run the `bash script/bc/libero_10_bc_mamba_dec.sh ` script, firstly I was facing this error (which is present in all the scripts I tried):

  ```
warnings.warn(msg, UserWarning)
In 'benchmark_libero10': Could not find 'agents/bc_mamba'

Available options in 'agents':
        act_agent
        bc_agent
        bc_mamba_dec
        bc_mamba_encdec
        bc_transformer_dec
        bc_transformer_encdec
        goal_bc_mamba_dec
        goal_bc_mamba_encdec
        goal_bc_transformer_dec
        goal_bc_transformer_encdec
        goal_ddpm_mamba_dec
        goal_ddpm_mamba_encdec
        goal_ddpm_transformer_dec
        goal_ddpm_transformer_encdec
        oc_ddpm_mamba_dec
        oc_ddpm_mamba_encdec
        oc_ddpm_transformer_dec
        oc_ddpm_transformer_encdec
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/mtiezzi/Projects/inProgress/MaIL/config
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
which I solved by changing the script call from `--multirun agents=bc_mamba` to `--multirun agents=bc_mamba_dec `.
Then, running the script it throws the error:

```
[2025-03-20 23:56:14,152][HYDRA]        #1 : agents=bc_mamba_dec agent_name=bc_mamba wandb.project=3_seed group=bc_mamba obs_seq=1 n_layers=16 mamba_ssm_cfg.d_state=16 mamba_ssm_cfg.d_conv=4 seed=1
/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'benchmark_libero10': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[2025-03-20 23:56:14,227][HYDRA]        #2 : agents=bc_mamba_dec agent_name=bc_mamba wandb.project=3_seed group=bc_mamba obs_seq=1 n_layers=16 mamba_ssm_cfg.d_state=16 mamba_ssm_cfg.d_conv=4 seed=2
[2025-03-20 23:56:14,298][HYDRA]        #3 : agents=bc_mamba_dec agent_name=bc_mamba wandb.project=3_seed group=bc_mamba obs_seq=5 n_layers=16 mamba_ssm_cfg.d_state=16 mamba_ssm_cfg.d_conv=4 seed=0
[2025-03-20 23:56:14,370][HYDRA]        #4 : agents=bc_mamba_dec agent_name=bc_mamba wandb.project=3_seed group=bc_mamba obs_seq=5 n_layers=16 mamba_ssm_cfg.d_state=16 mamba_ssm_cfg.d_conv=4 seed=1
[2025-03-20 23:56:14,441][HYDRA]        #5 : agents=bc_mamba_dec agent_name=bc_mamba wandb.project=3_seed group=bc_mamba obs_seq=5 n_layers=16 mamba_ssm_cfg.d_state=16 mamba_ssm_cfg.d_conv=4 seed=2
Error executing job with overrides: ['agents=bc_mamba_dec', 'agent_name=bc_mamba', 'wandb.project=3_seed', 'group=bc_mamba', 'obs_seq=1', 'n_layers=16', 'mamba_ssm_cfg.d_state=16', 'mamba_ssm_cfg.d_conv=4', 'seed=0']
Error in call to target 'agents.models.bc.bc_agent.BC_Agent':
InstantiationException('Error in call to target \'agents.models.bc.bc_agent.BC_Policy\':\nInstantiationException("Error locating target \'agents.module.vision.get_model.get_resnet\', set env var HYDRA_FULL_ERROR=1 to see chained exception.\\nfull_key: obs_encoder.rgb_model")\nfull_key: model')
full_key: agents

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```
With `HYDRA_FULL_ERROR=1`:

```
Traceback (most recent call last):
  File "/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'agents.models.oc_ddpm' has no attribute 'mamba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi/envs/robo2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/mtiezzi/Projects/inProgress/MaIL/agents/models/oc_ddpm/mamba.py", line 14, in <module>
    from mamba_ssm.modules.mamba_simple import Mamba, Block
ImportError: cannot import name 'Block' from 'mamba_ssm.modules.mamba_simple' (/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/mamba_ssm/modules/mamba_simple.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'agents.models.oc_ddpm.mamba.MixerModel':
ImportError("cannot import name 'Block' from 'mamba_ssm.modules.mamba_simple' (/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/mamba_ssm/modules/mamba_simple.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi/Projects/inProgress/MaIL/agents/models/bc/transformer.py", line 317, in __init__
    self.encoder = hydra.utils.instantiate(encoder)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi/envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'agents.models.oc_ddpm.mamba.MixerModel', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: encoder

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi/Projects/inProgress/MaIL/agents/models/bc/bc_agent.py", line 36, in __init__
    self.model = hydra.utils.instantiate(model).to(device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'agents.models.bc.transformer.Enc_only':
InstantiationException("Error locating target 'agents.models.oc_ddpm.mamba.MixerModel', set env var HYDRA_FULL_ERROR=1 to see chained exception.\nfull_key: encoder")
full_key: model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi/Projects/inProgress/MaIL/agents/models/bc/bc_agent.py", line 88, in __init__
    super().__init__(model=model, trainset=trainset, valset=valset, train_batch_size=train_batch_size,
  File "/home/mtiezzi/Projects/inProgress/MaIL/agents/base_agent.py", line 33, in __init__
    self.model = hydra.utils.instantiate(model).to(device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'agents.models.bc.bc_agent.BC_Policy':
InstantiationException('Error in call to target \'agents.models.bc.transformer.Enc_only\':\nInstantiationException("Error locating target \'agents.models.oc_ddpm.mamba.MixerModel\', set env var HYDRA_FULL_ERROR=1 to see chained exception.\\nfull_key: encoder")\nfull_key: model')
full_key: model

The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "/home/mtiezzi/Projects/inProgress/MaIL/run_benchmark.py", line 73, in <module>
    main()
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
            ^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 181, in sweep
    _ = r.return_value
        ^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi/Projects/inProgress/MaIL/run_benchmark.py", line 49, in main
    agent = hydra.utils.instantiate(cfg.agents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mtiezzi//envs/robo2/lib/python3.12/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'agents.models.bc.bc_agent.BC_Agent':
InstantiationException('Error in call to target \'agents.models.bc.bc_agent.BC_Policy\':\nInstantiationException(\'Error in call to target \\\'agents.models.bc.transformer.Enc_only\\\':\\nInstantiationException("Error locating target \\\'agents.models.oc_ddpm.mamba.MixerModel\\\', set env var HYDRA_FULL_ERROR=1 to see chained exception.\\\\nfull_key: encoder")\\nfull_key: model\')\nfull_key: model')
full_key: agents
```
